OnlineOrdering/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineOrdering.Models;
using OnlineOrderingBusiness;
using OnlineOrderingBusiness.Repositories;

namespace OnlineOrdering.Controllers
{
    [Authorize]
    public class CustomerController : Controller
    {
        // GET: Customer
        public ActionResult Customers()
        {
            var repository = new CustomerRepository();
            var model = repository.GetCustomers().Select(c => new CustomerModel
            {
                CustomerId = c.CustomerId,
                FirstName = c.FirstName,
                LastName = c.LastName,
                MiddleI = c.MiddleI
            }).ToList();
            
            return View(model);
        }

        [HttpGet]
        public ActionResult CreateCustomer()
        {
            var model = new CustomerModel();
            model.CustomerId = Guid.NewGuid();
            var billingAddress = new AddressModel { AddressId = Guid.NewGuid(), AddressTypeId = 0, CustomerId = model.CustomerId };
            var shippingAddress = new AddressModel { AddressId = Guid.NewGuid(), AddressTypeId = 1, CustomerId = model.CustomerId };
            model.AddressList = new List<AddressModel> {billingAddress, shippingAddress};

            return View(model);

        }

        [HttpPost]
        public ActionResult CreateCustomer(CustomerModel customerModel)
        {
            var customer = new Customer();
            CustomerFromCustomerModel(customerModel, customer);
            foreach (var addressModel in customerModel.AddressList)
            {
                var a = new Address();
                AddressFromAddressModel(a, addressModel);
                customer.Addresses.Add(a);
            }
           

            var repository = new CustomerRepository();
            repository.CreateCustomer(customer);
            return RedirectToAction("Customers");

        }

        [HttpGet]
        public ActionResult EditCustomer(Guid id)
        {
            var repository = new CustomerRepository();
            var customer = repository.GetCustomer(id);
            var model = CustomerModelFromCustomer(customer);

            return View(model);
        }

       

        [HttpPost]
        public ActionResult EditCustomer(CustomerModel customerModel)
        {
            var repository = new CustomerRepository();
            var customer = repository.GetCustomer(customerModel.CustomerId);
            CustomerFromCustomerModel(customerModel, customer);
            foreach (var addressModel in customerModel.AddressList)
            {
                var address = customer.Addresses.FirstOrDefault(a => a.AddressId == addressModel.AddressId);
                AddressFromAddressModel(address,addressModel);
            }

            repository.EditCustomer(customer);
            return RedirectToAction("Customers");
        }

        public ActionResult DeleteCustomer(Guid id)
        {
            var repository = new CustomerRepository();
            repository.DeleteCustomer(id);
            return RedirectToAction("Customers");
        }

        private AddressModel AddressModelFromAddress(Address address)
        {
            return new AddressModel
            {
                AddressId = address.AddressId,
                AddressTypeId = address.AddressTypeId,
                CustomerId = address.CustomerId,
                StreetAddress = address.StreetAddress,
                City = address.City,
                State = address.State,
                Zip = address.Zip
            };
        }

        public void AddressFromAddressModel(Address a, AddressModel model)
        {

            a.AddressId = model.AddressId;
            a.AddressTypeId = model.AddressTypeId;
            a.CustomerId = model.CustomerId;
            a.StreetAddress = model.StreetAddress;
            a.City = model.City;
            a.State = model.State;
            a.Zip = model.Zip;

        }

        private void CustomerFromCustomerModel(CustomerModel customerModel, Customer customer)
        {
            customer.CustomerId = customerModel.CustomerId;
            customer.FirstName = customerModel.FirstName;
            customer.LastName = customerModel.LastName;
            customer.MiddleI = customerModel.MiddleI;
            
        }

        private CustomerModel CustomerModelFromCustomer(Customer customer)
        {
            var model = new CustomerModel
            {
                CustomerId = customer.CustomerId,
                FirstName = customer.FirstName,
                LastName = customer.LastName,
                MiddleI = customer.MiddleI
            };

            model.AddressList = new List<AddressModel>();

            foreach (var address in customer.Addresses.OrderBy(a=>a.AddressTypeId))
            {
                var addressModel = AddressModelFromAddress(address);
                model.AddressList.Add(addressModel);
            }

            return model;
        }
    }
}

OnlineOrdering/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineOrdering.Models;
using OnlineOrderingBusiness;
using OnlineOrderingBusiness.Repositories;

namespace OnlineOrdering.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        [HttpGet]
        public ActionResult ViewOrders()
        {
            var repository = new OrderRepository();
            var orderModelList = repository.GetOrders().Select(o => new OrderModel
            {
                OrderId = o.OrderId,
                CustomerName = String.Format("{0} {1}", o.Customer.FirstName, o.Customer.LastName),
                OrderCode = o.OrderCode,
                OrderDateTime = o.OrderDateTime,
                OrderTotal = o.OrderTotal
            });
            return View(orderModelList);
        }


        [HttpGet]
        public ActionResult CreateOrder()
        {
            var repository = new CustomerRepository();
            var customerDictionary =
                repository.GetCustomers()
                    .Select(c => new {CustomerId = c.CustomerId, CustomerName = c.FirstName + " " + c.LastName})
                    .ToDictionary(x => x.CustomerId, x => x.CustomerName);
            var model = new OrderModel
            {
                OrderId = Guid.NewGuid(),
                OrderDateTime = DateTime.Now,
                CustomerDictionary = customerDictionary
            };
            return View(model);
        }


        [HttpPost]
        public ActionResult CreateOrder(OrderModel model)
        {
            var orderRepository = new OrderRepository();
            var order = new Order
            {
                OrderId = model.OrderId,
                OrderDateTime = model.OrderDateTime,
                CustomerId = model.CustomerId

            };
            orderRepository.CreateOrder(order);
            return RedirectToAction("AddItem", new {id = model.OrderId});
        }


    [HttpGet]
        public ActionResult AddItem(Guid id)
        {
            var repository = new ProductRepository();
            var productDictionary = repository.GetProducts().OrderBy(product => product.ProductName)
                .Select(p => new {ProductId = p.ProductId, ProductName = p.ProductName})
                .ToDictionary(x => x.ProductId, x => x.ProductName);
            var quantityDictionary = new Dictionary<int, int>();
            for (int i = 1; i <= 10; i++)
            {
                quantityDictionary.Add(i, i);
            }
            var model = new OrderItemModel
            {
                OrderItemId = Guid.NewGuid(),
                OrderId = id,
                OrderItemTotal = 0.ToString("c"),
                ProductDictionary = productDictionary,
                QuantityDictionary = quantityDictionary
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult AddItem(OrderItemModel model)
        {
            var orderItem = new OrderItem
            {
                OrderId = model.OrderId,
                OrderItemId = Guid.NewGuid(),
                OrderItemTotal = Convert.ToDecimal(model.OrderItemTotal.Replace("$", "")),
                ProductId = model.ProductId,
                Quantity = model.Quantity
            };
            var repository = new OrderRepository();
            repository.AddOrderItem(orderItem);
            return RedirectToAction("ViewOrder", new {id = model.OrderId});
        }


        [HttpGet]
        public ActionResult ViewOrder(Guid id)
        {
            var repository = new OrderRepository();
            var order = repository.GetOrder(id);
            var model = new OrderModel
            {
                OrderId = order.OrderId,
                OrderCode = order.OrderCode,
                OrderDateTime = order.OrderDateTime,
                CustomerName = String.Format("{0} {1}", order.Customer.FirstName, order.Customer.LastName),
                OrderTotal = order.OrderTotal
            };
            model.OrderItems = order.OrderItems.Select(oi => new OrderItemModel
            {
                OrderItemId = oi.OrderItemId,
                OrderId = oi.OrderId,
                ProductName = oi.Product.ProductName,
                Quantity = oi.Quantity,
                OrderItemTotal = oi.OrderItemTotal.ToString("c")
            }).ToList();

            return View(model);
        }


        public JsonResult GetOrderItemTotal(Guid productId, int quantity)
        {
            var repository = new ProductRepository();
            var unitCost = repository.GetProduct(productId).Price;
            var orderItemTotal = unitCost*quantity;
            return Json(new {orderItemTotal = orderItemTotal}, JsonRequestBehavior.AllowGet);
        }

    }
}

OnlineOrdering/Views/Shared/ViewOrderItems.cshtml
@model IEnumerable<OnlineOrdering.Models.OrderItemModel>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderItemId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderItemTotal)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OrderItemId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderItemTotal)
        </td>
    </tr>
}

</table>

OnlineOrdering/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Online Order</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Online Order", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Customers", "Customers", "Customer")</li>
                        <li>@Html.ActionLink("Orders", "ViewOrders", "Order")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Online Ordering</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>